name: nuscenes-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - pip
  - pip:
      - nuscenes-devkit==1.1.10
      - opencv-python
      - pyquaternion
      - open3d